##异常
Throwable
* Error：错误无法治愈的毛病，必须改源代码
* Exception：异常处理掉程序可以继续执行


###Exception
Exception:编译期异常，进行编译程序时出的问题
RuntimeException:运行期异常

异常产生过程解析

####throw
```java
 int[] arr ={1,2,3};
    method(null);


    }


    public static void method(Object obj){
       Objects.requireNonNull(obj,"空指针");

    }
```

###声明异常throws
把异常对象生命抛出给方法的调用者处理，最终交给JVM-->中断处理
```java
  public static void main(String[] args) throws FileNotFoundException {
    readFile("aaaav");


    }


    public static void readFile(String fileName) throws FileNotFoundException {
        if (!fileName.equals("ccccv")){
            throw new FileNotFoundException("文件传递的路径不对");
        }
    }
    
```

###try...catch
1.try中可能回抛出多个异常对象，那么就可以使用多个catch来处理这些异常对象
2.如果try中产生了异常，那么就会执行catch中的异常处理逻辑错，执行完毕catch中的处理逻辑，继续执行try...catch之后的代码



###Throwable类
3个异常处理的方法：
```java
public String getMessage()//返回此throwable的详细消息字符串。 
public String toString()//返回此throwable的简短描述。 
public void printStackTrace()//JVM打印异常对象，默认此方法，打印的异常信息是最全面的
```

###finally代码块
有一些特定的代码无论异常是否发生，都要执行。
finally不能单独使用，必须跟try一起使用
finally一般用于资源释放（资源回收），无论程序是否出现异常，最后都要资源释放（IO）

###异常处理方法
1.多个异常分别处理
```java
 try {
           int[] arr = {1,2,3};
           System.out.println(arr[3]);
       }catch (ArrayIndexOutOfBoundsException e){
           System.out.println(e);
       }

       try {
           List<Integer> list = List.of(1,2,3);
           System.out.println(list.get(3));
       }catch (IndexOutOfBoundsException e){
           System.out.println(e);
       }

```

2.多个异常一次捕获多次处理(用的比较多)
一个try多个catch注意事项：
catch里面定义的异常变量，如果有子父类关系，那么子类的异常变量必须写在上边，否则就会报错
```java
 try {
           int[] arr = {1,2,3};
           System.out.println(arr[3]);
           List<Integer> list = List.of(1,2,3);
           System.out.println(list.get(3));
       }catch (ArrayIndexOutOfBoundsException e){
           System.out.println(e);
       }catch (IndexOutOfBoundsException e){
           System.out.println(e);
       }
```

3.多个异常一次捕获一次处理
Exception

如果finally有return语句，永远返回finally中的结果，要避免该情况
```java
 public static void main(String[] args) {
        int a = getA();
        System.out.println(a);

    }
    public static int getA(){
        int a=10;
        try {
            return a;
        }catch (Exception e){
            System.out.println(e);
        }finally {
            a=100;
            return a;
        }
    }
```
结果100

###异常的注意事项
子父类异常：
如果父类抛出了多个异常，子类重写父类方法时，抛出和父类相同的异常或者是父类异常的子类或者不跑出异常。
父类方法没有抛出异常，子类重写父类该方法时也不可抛出异常。此时子类产生该异常，只能捕获处理，不能声明抛出。
注：父类异常时什么样，子类异常就什么样
```java
public class Fu {
    public void show01() throws NullPointerException,ClassCastException{}
    public void show02() throws IndexOutOfBoundsException{}
    public void show03() throws IndexOutOfBoundsException{}
    public void show04() {}
        
}

class Zi extends Fu{
    //子类重写父类方法的时候，抛出和父类相同的异常
    public void show01()throws NullPointerException,ClassCastException{}
    //子类重写父类的时候，抛出和父类异常的子类
    public void show02()throws ArrayIndexOutOfBoundsException{}
    //子类重写父类的时候，不抛出异常
    public void show03(){}
    //此时子类产生该异常，只能捕获处理不能声明抛出
    public void show04(){
        try {
            throw new Exception("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
        }
```


